# Generated by Django 4.2.6 on 2023-10-31 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vaga', models.CharField(blank=True, max_length=255, verbose_name='Título da vaga')),
                ('descricao_vaga', models.TextField(verbose_name='Descrição da vaga')),
                ('dt_criacao_vaga', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('dono_vaga', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.FileField(upload_to='curriculos/')),
                ('dt_canditato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da candidatura')),
                ('cadidato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadidato')),
                ('vaga', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vaga_para_voce.vagas', verbose_name='Vaga')),
            ],
        ),
    ]
